# Generated by Django 4.2.4 on 2024-03-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_servicio_codigoservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='codigoServicio',
        ),
    ]
